/*
 * This source file was generated by the Gradle 'init' task
 */
package visualstudiocode;

public class App {
    public static void main(String[] args) {
        HelloWorldClass helloWorld = new HelloWorldClass(); // Creating an object of HelloWorldClass
        System.out.println(helloWorld.getGreeting()); // Calling the getGreeting method and printing the result
    }
}